### ISSUE TITLE
Code doesn't work on remote server

### ISSUE THREAD

**Issue by dtch1997** [dtch1997/neural_clbf#5]
It's very strange, it runs fine on my laptop, but on the remote server I get this error: 

```
Traceback (most recent call last):                                                                   
  File "neural_clbf/training/train_inverted_pendulum.py", line 149, in <module>                      
    main(args)                                                                                       
  File "neural_clbf/training/train_inverted_pendulum.py", line 49, in main                           
    dynamics_model = InvertedPendulum(                                                               
  File "/home/daniel/.cache/pypoetry/virtualenvs/isaacgymenvs-0vPp-7rO-py3.8/lib/python3.8/site-packa
ges/neural_clbf/systems/inverted_pendulum.py", line 59, in __init__                                  
    super().__init__(                                                                                
  File "/home/daniel/.cache/pypoetry/virtualenvs/isaacgymenvs-0vPp-7rO-py3.8/lib/python3.8/site-packages/neural_clbf/systems/control_affine_system.py", line 77, in __init__
    self.compute_linearized_controller(scenarios)
  File "/home/daniel/.cache/pypoetry/virtualenvs/isaacgymenvs-0vPp-7rO-py3.8/lib/python3.8/site-packages/neural_clbf/systems/control_affine_system.py", line 146, in compute_linearized_controller
    K_np = lqr(A, B, Q, R)
  File "/home/daniel/.cache/pypoetry/virtualenvs/isaacgymenvs-0vPp-7rO-py3.8/lib/python3.8/site-packages/neural_clbf/systems/utils.py", line 39, in lqr 
    X = scipy.linalg.solve_discrete_are(A, B, Q, R)
  File "/home/daniel/.cache/pypoetry/virtualenvs/isaacgymenvs-0vPp-7rO-py3.8/lib/python3.8/site-packages/scipy/linalg/_solvers.py", line 716, in solve_discrete_are
    raise LinAlgError('Failed to find a finite solution.')
numpy.linalg.LinAlgError: Failed to find a finite solution
```

**Comment by dtch1997** [comment]
Fixed by reinstalling dependencies... I guess there was just some weirdness going on?
